dataset_params:
  train_dir: ../datasets/train
  test_dir: ../datasets/test
  frame_shape: [256, 256, 3]
  num_sources: 2
  target_delta: 2
  base_layer: False
  use_saliency_map: False
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
    

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: "gist_rainbow"

eval_params:
  ref_codec: 'hevc' #[hevc, vvc, vvenc]
  qp: 30 #HEVC_QPS [50,45,40,35,30]
  metrics: ['lpips','dists', 'msVGG', 'fsim', 'ms_ssim', 'psnr','vmaf']
  temporal: False
  num_frames: 128 #First N frames compressed from an input video
  gop_size: 32 #Number of P frames = gop_size-1
  rd_point: 0
  fps: 20 #frame-rate for bitrate computation